### ISSUE TITLE
 Update application to use Reportlab 3.0 for 2.7 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#47] opened 2015-10-23 15:29 UTC

**Comment by CTLocalGovTeam** [comment] 2015-11-19 06:49
@LindsayThomas 
The latest version of reportlab is 3.2.0. We are upgrading to this version of Reportlab.

An additional note from reportlab website. Installers (.exe) are no longer available.
>2.3 Windows Packages 
>-------------------- 
>We no longer made .exe or .msi files. We provide ``.whl`` files with compiled 
>C extensions for all supported python versions at 
>
>http://pypi.python.org/pypi/reportlab/ 
>
>These may be installed using recent `pip` or other competent distribution 
>package. If you aren't comfortable with the command line, we recommend pip-win: 
>https://sites.google.com/site/pydatalog/python/pip-for-windows 

Just thought of mentioning the above, because you'd have to update the documentation too.

**Comment by ScottOppmann** [comment] 2015-11-19 12:08
@busbus - Please review.

**Comment by busbus** [comment] 2015-12-01 00:48
I found this install confusing - and not sure if I even correctly installed the new version of ReportLab.  I ended up updating all the site packages using the batch command (updated my pre-existing ReportLab library to 3.2).  

@CTLocalGovTeam  Is this the correct procedure?

**Comment by CTLocalGovTeam** [comment] 2015-12-01 06:47
@busbus 
If you already have pip installed then you'll have to run the following command:
`pip install reportlab --upgrade reportlab` in both python environments (Desktop and Server)

If you do not have pip installed, then use pip-for-windows, point to location of python interpreter for ArcGIS Desktop and Server (python.exe) and run the following command:
`pip install reportlab` in both environments

**Comment by busbus** [comment] 2015-12-01 21:12
Let's revert this change and support python 3.0 with an .exe install.

This will be easier for our users and will be consistent with the Site Selector application.

**Comment by CTLocalGovTeam** [comment] 2015-12-02 07:30
@busbus,
Assuming that you mean Reportlab 3.0 instead of Python 3.0.

We did not need to make any code changes when we upgraded from Reportlab 2.7 to 3.2, so we expect the upgrade to Reportlab 3.0 should also be smooth. However we need to test report generation thoroughly with 3.0.

Here are the installers for 3.0 that we are going to use. Please confirm.  
http://www.reportlab.com/ftp/reportlab-3.0.win32-py2.7.exe
http://www.reportlab.com/ftp/reportlab-3.0.win-amd64-py2.7.exe

**Comment by busbus** [comment] 2015-12-02 15:33
Yes - Reportlab - thanks for correcting.  

Confirmed on the installs.

**Comment by busbus** [comment] 2016-01-06 23:19
Fixed with 4.7

**Closed by busbus** 2016-01-06 23:19 UTC
